### ISSUE TITLE
Throttle the bandwidth of our joystick topic

### ISSUE THREAD

**Issue by jmblixt3** [GOFIRST-Robotics/LUNABOTICS-2023#10]
We need to set a bandwidth limit on the joystick topic.

**Comment by jmblixt3** [comment]
https://github.com/ros-tooling/topic_tools

**Comment by Isopod00** [comment]
joy_node parameters: http://wiki.ros.org/joy (we can probably just use the autorepeat_rate and coalesce_interval parameters to throttle our bandwidth? Should at leas be an easy thing to try)
